services:
  base:
    # built own version to prevent version mismatch when attempting
    # to run at later time
    image: "jimanx2/seek-robot-problem"
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - APP_ENV=${APP_ENV:-development}
    profiles: 
      - build

  server:
    image: "jimanx2/seek-robot-problem"
    volumes:
      - ${PWD}:/srv
    ports:
      - 3000:3000
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    entrypoint: ["/usr/local/bin/bundle", "exec", "rackup", "-o", "0.0.0.0", "-p", "3000"]
  
  worker:
    image: "jimanx2/seek-robot-problem"
    volumes:
      - ${PWD}:/srv
    environment:
      - QUEUE=robot
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    entrypoint: ["/usr/local/bin/bundle", "exec", "rake", "resque:work"]

  cli:
    image: "jimanx2/seek-robot-problem"
    volumes:
      - ${PWD}:/srv
    ports:
      - 3000:3000
    entrypoint: ["/usr/local/bin/bundle", "exec", "rake"]
    user: 1000:1000
    profiles:
      - cli

  redis:
    image: redis:alpine