source "https://rubygems.org"

# require exact ruby version
ruby "~> 3.4"

# task management
gem 'rake'

# (unit) testing
gem 'rspec', :group => :development
gem "rspec-roda", "~> 0.2.0", :group => :development
gem "mock_redis", "~> 0.49.0", :group => :development

# api server deps
gem "roda"
gem "rack"
gem "rackup", "~> 2.2"
gem "webrick", "~> 1.9"
gem "redis", "~> 5.3"
gem "thor", "~> 1.3"
gem "resque", "~> 2.7"
gem "resque-retry", "~> 1.8"
gem "resque_spec", "~> 0.18.1"
gem "ruby-prof", "~> 1.7"
