source "https://rubygems.org"

# require exact ruby version
ruby "~> 3.4"

# task management
gem 'rake'

# (unit) testing
gem 'rspec'

# api server deps
gem "roda"
gem "rack"
gem "rackup", "~> 2.2"
gem "webrick", "~> 1.9"
gem "redis", "~> 5.3"
gem "thor", "~> 1.3"
gem "resque", "~> 2.7"
gem "resque-retry", "~> 1.8"
