require 'rspec/core'
require 'rspec/core/rake_task'
require_relative 'spec/support/inherit_from_matcher'
require 'commands/command_generator'

# Define the "spec" task, at task load time rather than inside another task
RSpec::Core::RakeTask.new(:spec) do |t|
    t.rspec_opts = "--format documentation"
end

RSpec.configure do |config|
    config.include InheritFromMatcher
end

task default: %w[non-interactive]

desc 'Run all tests, even those usually excluded.'
task :test do 
    ENV['RUN_ALL_TESTS'] = 'true'
    Rake::Task['spec'].invoke
end

cmd_args = (ARGV[2..-1].nil? ? [] : ARGV[2..-1]).join(' ')
debug_flag = "-d" if !cmd_args.index("-d") && !ENV['DEBUG'].nil? && ENV['DEBUG'] == "true"

desc "Runs the REPL for line by line command processing"
task :repl do
    ruby "main.rb -r #{debug_flag} #{cmd_args}", verbose: debug_flag == "-d"
end

desc "Runs the non-interactive processing for inputs from STDIN (piping)"
task :"non-interactive" do
    ruby "main.rb #{debug_flag} #{cmd_args}", verbose: debug_flag == "-d"
end

namespace :make do
    desc "Generate a new command class"
    task :command do 
        raise 'Please set the NAME environment value' if ENV['NAME'].nil? || ENV['NAME'].empty?
        CommandGenerator.start([ENV['NAME']])
    end
end

