require 'rspec/core/rake_task'

# Define the "spec" task, at task load time rather than inside another task
RSpec::Core::RakeTask.new(:spec) do |t|
    t.rspec_opts = "--format documentation"
end

task default: %w[non-interactive]

desc 'Run all tests, even those usually excluded.'
task :test do 
    ENV['RUN_ALL_TESTS'] = 'true'
    Rake::Task['spec'].invoke
end

cmd_args = (ARGV[2..-1].nil? ? [] : ARGV[2..-1]).join(' ')
debug_flag = "-d" if !cmd_args.index("-d") && !ENV['DEBUG'].nil? && ENV['DEBUG'] == "true"

task :repl do
    ruby "main.rb -r #{debug_flag} #{cmd_args}", verbose: debug_flag == "-d"
end

task :"non-interactive" do
    ruby "main.rb #{debug_flag} #{cmd_args}", verbose: debug_flag == "-d"
end
